### PR TITLE
Correctly decode a Media manifest with BYTERANGE

### LINKED ISSUE #46: Issues related to iframe playlist and bytes ranges
In Reader.Go:
in the following line:
**case !state.tagIframeStreamInf && strings.HasPrefix(line, "#EXT-X-I-FRAME-STREAM-INF:"):**
you use only the first iframe manifest found and not all.

also, the playlist iframe segments has no offset and linit due to lin "} else if state.tagRange { " in:

case !strings.HasPrefix(line, "#"):
		if state.tagInf {
			p.Append(line, state.duration, title)
			state.tagInf = false
		} else if state.tagRange { 

because i have state.tagInf and state.tagRange so "else if " isnt good enough and should be:

if state.tagInf {
			p.Append(line, state.duration, title)
			state.tagInf = false
		}
if state.tagRange {

### PR DESCRIPTION
**Pull request by bradleyfalzon**
decodeLineOfMediaPlaylist currently expects a playlist to have
*either* a EXTINF or a EXT-X-BYTERANGE because it's using an
if EXTINF {} else if EXT-X-BYTERANGE {}, this is incorrect as
EXTINF is required and therefore a playlist must always have
an EXTINF, the EXT-X-BYTERANGE is optional.

This change also fixes a bug when an offset given in EXT-X-BYTERANGE
does not reset its state, so segments without an offset would
incorrectly be given the offset of a previous segment.

Also includes unit tests to reproduce the issue.

Fixes #46

### CODE REVIEW

**Comment by bradleyfalzon** [comment]
@AyliD can you also check over this PR and verify it resolves your issue?

**Comment by AyliD** [comment]
@bradleyfalzon  you are an angel, seems like the fix i made and working well for me  (but i didnt write any unitesting) so thank you!

**Comment by bradleyfalzon** [comment]
Thanks for the issue and fixes, unless urgent I'll leave these around for 24hrs and let @grafov make any further suggestions/clarifications before merging.

**Comment by grafov** [comment]
@AyliD thank you for explaining the problem!
@bradleyfalzon I think fix is ok, let merge it.

**Pull request merged**
